PR for homework #4
otus-devops-2019-02/der-andrew_infra pull request #1
Opened 2019-03-17 16:31 UTC by der-andrew

# Выполнено ДЗ № 4

 - [ v] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
git clone git@github.com:otus-devops-2019-02/der-andrew_infra.git
cd der-andrew_infra/
git checkout -b play-travis
git branch
mkdir .github
cd .github/
wget http://bit.ly/otus-pr-template -O PULL_REQUEST_TEMPLATE.md
git add PULL_REQUEST_TEMPLATE.md 
git commit -m 'Add PR template'
PULL_REQUEST_TEMPLATE.md it push --set-upstream origin play-travis
git push --set-upstream origin play-travis

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
В вашем Pull request должны появиться следующие файлы:
.github/PULL_REQUEST_TEMPLATE.md

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2019-03-17 17:25 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. В данном задании вам нужно провести интеграцию гихаба с тревисом для выполнения тестов. Инструкция есть в личном кабинете. Пока возвращаю на доработку.

2019-03-17 19:23 UTC, der-andrew commented
Понятно. Так сделано. Ошибка исправлена. Тревис рад)
https://travis-ci.com/otus-devops-2019-02/der-andrew_infra/builds/104714154

2019-03-17 19:25 UTC, der-andrew commented
Какой-то сплитбрейн с часовыми поясами... Не обращай внимания.

2019-03-18 05:23 UTC, mrgreyves approved these changes
Здравствуйте!) Проверил. Хорошо что разобрались с тревисом и починкой приложения. ДЗ принимаю!=)

2019-03-18 05:47 UTC, merged