Cloud bastion
otus-devops-2019-02/der-andrew_infra pull request #2
Opened 2019-03-21 19:23 UTC by der-andrew

# Выполнено ДЗ № 3
Знакомство с облачной
инфраструктурой. Google
Cloud Platform

 - [ v] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
- Создание учетной записи в GCP
- Добавлен ssh ключ в GCP
- Создание в веб-интерфейсе инстансов ВМ и подключение к ним по SSH
- Созданиме и применение правил фаервола в VPC
- Создан VPN туннель с помощбю pritunl

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2019-03-22 05:49 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. К сожалению тесты тревиса не прошли. Вполне возможно хост с впн был выключен во время тестов тревиса. Постарайтесь починить тесты. Пока возвращаю на доработку.

2019-03-22 06:11 UTC, der-andrew commented
> Здравствуйте!) Проверил ваше дз. К сожалению тесты тревиса не прошли. Вполне возможно хост с впн был выключен во время тестов тревиса. Постарайтесь починить тесты. Пока возвращаю на доработку.

Машины работают постоянно... странно. Руками захожу на обе тачки и по ВПН и по ссш.
Ну да ладно, буду дружить их с тревисом.

2019-03-24 09:17 UTC, der-andrew commented
как же задание может быть выполнено, если результаты моей работы в бранче cloud-bastion, а клонируется бранч  master???
`git clone --depth=50 https://github.com/otus-devops-2019-02/der-andrew_infra.git otus-devops-2019-02/der-andrew_infra`

а чтобы результаты попали в мастер, нужно заопрувить PR, а для этого нужно, чтобы отработал тревис, а тревис валится потомучто результаты не в мастере.....
петля.....

2019-03-24 09:18 UTC, der-andrew commented
как же задание может быть выполнено, если результаты моей работы в бранче cloud-bastion, а клонируется бранч  master???
`git clone --depth=50 https://github.com/otus-devops-2019-02/der-andrew_infra.git otus-devops-2019-02/der-andrew_infra`

а чтобы результаты попали в мастер, нужно заопрувить PR, а для этого нужно, чтобы отработал тревис, а тревис валится потомучто результаты не в мастере.....
петля.....

2019-03-24 09:21 UTC, mrgreyves commented
![image](https://user-images.githubusercontent.com/34331259/54877400-41731000-4e2f-11e9-9a71-d12f5b669c2b.png)
Здравствуйте!) Тревис клонирует нужную ветку.

2019-03-24 09:50 UTC, der-andrew commented
вероятно должен, но у меня вот так
![image](https://user-images.githubusercontent.com/40394363/54877725-52258500-4e33-11e9-8b1d-48ad2fd70ed2.png)

2019-03-24 09:51 UTC, der-andrew commented
О! уже поправили?) новый билд строился с правильной ссылкой

2019-03-24 09:57 UTC, mrgreyves commented
Нет, я посмотрел из последнего билда)

2019-03-24 10:01 UTC, der-andrew commented
Где-то закавыка в README.md Всё ли верно в форматах айпишников?
`# der-andrew_infra                                                                                                                                                                                          
der-andrew Infra repository                                                                                                                                                                                 
                                                                                                                                                                                                            
[*]                                                                                                                                                                                                         
Исследовать способ подключения к someinternalhost в одну команду                                                                                                                                            
из вашего рабочего устройства, проверить работоспособность найденного решения и внести его в                                                                                                                
README.md в вашем репозитории.                                                                                                                                                                              
                                                                                                                                                                                                            
1. Method one.                                                                                                                                                                                              
ssh -i ~/.ssh/GCP-appuser -t appuser@35.233.10.136 -A ssh appuser@10.132.0.6                                                                                                                                
2. Method two.                                                                                                                                                                                              
ssh -J appuser@35.233.10.136 appuser@10.132.0.6                                                                                                                                                             
В обоих случаях агент должен работать с добавленным ключом ессесна)                                                                                                                                         
                                                                                                                                                                                                            
Добавляем алиас на понравившийся метод                                                                                                                                                                      
alias ssh2someinthost='ssh -J appuser@35.233.10.136 appuser@10.132.0.6'                                                                                                                                     
                                                                                                                                                                                                            
========================================================================                                                                                                                                    
                                                                                                                                                                                                            
                                                                                                                                                                                                            
bastion_IP = 35.233.10.136                                                                                                                                                                                  
someinternalhost_IP = 10.132.0.6                                                                                                                                                                            
`

2019-03-24 10:47 UTC, mrgreyves commented
Обозначение для хостов должно быть строго такое же как и в методичке =)

2019-03-24 11:00 UTC, der-andrew commented
У меня всё верно, однако тревис ругается
![image](https://user-images.githubusercontent.com/40394363/54878386-08419c80-4e3d-11e9-9a7f-02bbd3231fe7.png)

2019-03-24 14:29 UTC, der-andrew commented
I need help! Уже не знаю куда капнуть

2019-03-24 15:29 UTC, mrgreyves commented
![image](https://user-images.githubusercontent.com/34331259/54881619-ba3f8f80-4e62-11e9-9941-af7d8587370a.png)
В две строки напиши, прямо как в методичке =)

2019-03-24 15:58 UTC, der-andrew commented
Ннну вы ребята даёте!!!!
Во что в методичке
![image](https://user-images.githubusercontent.com/40394363/54882006-d5ac9980-4e66-11e9-9641-d61b4d162f51.png)

2019-03-24 16:00 UTC, der-andrew commented
Я же написал в две строчки

2019-03-24 16:38 UTC, der-andrew commented
> ![image](https://user-images.githubusercontent.com/34331259/54881619-ba3f8f80-4e62-11e9-9941-af7d8587370a.png)
> В две строки напиши, прямо как в методичке =)

 Так и сделано - в две строчки. Просто на сайте .md так форматируется. Результат - провал. Ещё варианты?

2019-03-24 16:39 UTC, der-andrew commented
Тревис не может где-то у себя закешировать и не обновлять?

2019-03-24 17:03 UTC, mrgreyves commented
Сервер работает сейчас?)

2019-03-24 19:43 UTC, iphizic commented
Попробуйте в ридми заменить звездочку на 'x'.

2019-03-25 05:28 UTC, der-andrew commented
Не прокатило со звездой...

2019-03-25 06:11 UTC, iphizic commented
а что если в ридми добавить \n в конце первой строки с ip

2019-03-25 06:15 UTC, der-andrew commented
я уже пробовал так. более того, грешным делом скопипастил эти строки у сдавших коллег =->
может не будем гадать на кофейной гуще? какой-то траблшутинг тревиса имеется? хотябы посмотреть что он может распарсить, а что нет. и что он вообще парсит

2019-03-25 06:31 UTC, iphizic commented
Попробуй поставить отступы перед переменными хостов.

2019-03-25 06:43 UTC, iphizic commented
Как тебя в слаке найти?

2019-03-26 09:23 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув)

2019-03-26 10:31 UTC, merged